kind: apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: linconln/consumer:v1
    env:
      - name: RABBITMQ_HOST
        valueFrom:
          configMapKeyRef:
            name: rabbitmq
            key: rabbit
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000
