apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  selector:
    app: consumer
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-ferramentas
data:
  RABBITMQ_HOST: rabbitmq
  REDIS_HOST: redis
  REDIS_PORT: '6379'
  MINIO_ENDPOINT: minio:9000
  MINIO_ROOT_USER: guest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: linconln/consumer:2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

