apiVersion: v1
kind: Namespace
metadata:
  name: finance
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meu-app
  name: meu-app
  namespace: finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meu-app
  strategy: {}
  template:
    metadata:
      labels:
        app: meu-app
    spec:
      containers:
        - image: nginx
          name: meu-app
          ports:
            - containerPort: 81
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: meu-app
  name: meu-app
  namespace: finance
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 80
  selector:
    app: meu-app
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meu-app
  namespace: finance
spec:
  ingressClassName: meu-app
  rules:
    - host: meu-app.com
      http:
        paths:
          - backend:
              service:
                name: meu-app
                port:
                  number: 80
            path: /
            pathType: Prefix
status:
  loadBalancer: {}